platform :ios, '13.5'

target 'VBotSDKExample' do
  use_frameworks!
  
  pod 'VBotPhoneSDK', :path => './Lib/VBotPhoneSDK'
  
  target 'VBotSDKExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VBotSDKExampleUITests' do
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end



