platform :ios, '13.5'

target 'VBotSDKExample' do
 use_frameworks! :linkage => :static

  pod 'VBotPhoneSDK', :path => 'lib/VBotPhoneSDK'
  pod 'VBotSIP', :path => 'lib/VBotSIP'
  
  pod 'MBProgressHUD', '~> 1.2.0'
  
  target 'VBotSDKExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VBotSDKExampleUITests' do
    # Pods for testing
  end

end

